---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

- hosts: all
  vars_files: 
    - inventory.yml
  roles:
    - cli
    - gui
