---
- name: Add chrome source lists
  shell: sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
  become: true

- name: Add chrome key
  shell:  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  become: true

- name: Install chrome
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
     - google-chrome-stable
  become: true

