---
- name: Add docker gpg key
  shell: curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | sudo apt-key add -
  become: true

- name: Add source docker list
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo $ID) $(lsb_release -cs) stable"
  become: true

- name: Install docker
  apt:
    update_cache: yes
    name: docker-ce
  become: true

- name: Install docker-compose
  shell: curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  become: true

- name: Chmod docker-compose
  shell: chmod +x /usr/local/bin/docker-compose
  become: true

- name: Add user to docker group
  shell: usermod -a -G docker {{ username }}
  become: true
