---
- name: Install cli packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
     - vim
     - git
     - zsh
  become: true

- name: Enable zsh
  shell: chsh "{{ username }}" -s /bin/zsh
  become: true

- name: Install Oh My Zsh
  shell: SHELL="/bin/zsh" && sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

- name: Change Zsh theme
  shell: echo 'ZSH_THEME="amuse"' >> ~/.zshrc

- name: Install fuzzy finder
  shell: rm -Rf ~/.fzf && git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && yes | ~/.fzf/install

- include: docker.yml
- include: vim.yml
